name: Approval

on:
  push:
    branches:
      - test-approvals
  pull_request:
    branches:
      - test-approvals

jobs:
  approval:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["RC", "PROD"]
    environment: ${{ matrix.environment }}
    steps:
      - name: echo approval
        run: echo "Approved!! Huzzah!!"
      - name: echo commands
        run: echo ${{ matrix.environment }}
