on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test centralised actions
    steps:
      - name: Checkout private tools
        uses: actions/checkout@v3
        with:
          repository: sra405/github-actions
          token: ${{ secrets.GH_PAT }}
          path: .github/actions
      - uses: actions/checkout@v3
      - id: test_s3_params
        uses: .github/actions/s3-learning-resources
