# shamelessly stolen from:
# https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
name: Test inputs

on:
  workflow_dispatch:
    inputs:
      repo:
        required: true
      branch:
        type: choice
        description: Which branch to deploy
        options: 
        - master
        - draft
      dummy-boolean:
        required: false
        type: boolean
        description: Include  emojis

jobs:
  greet:
    runs-on: ubuntu-latest

    name: ${{ github.event.inputs.repo }} - ${{ github.event.inputs.branch }}
    caption: ${{ github.event.inputs.repo }} - ${{ github.event.inputs.branch }}

    steps:
    - name: Send greeting
      run: echo "Running '${{ github.event.inputs.repo }}' on branch '${{ github.event.inputs.branch }}'"
